DogruProjeSon/eyikat.com/DogruProje/eYikat/eYikat/Areas/Admin/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eYikat.Areas.Admin.Controllers
{
    [Authorize(Roles = "yonetici")]
    public class AdminHomeController : Controller
    {
        // GET: Admin/AdminHome
        public ActionResult Index()
        {
            return View();
        }
    }
}

DogruProjeSon/eyikat.com/DogruProje/eYikat/eYikat/Areas/Admin/Controllers/IlanlarController.cs
using eYikat.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eYikat.Areas.Admin.Controllers
{
    public class IlanlarController : Controller
    {
        eYikatEntities2 db = new eYikatEntities2();
        // GET: Admin/Ilanlar
        public ActionResult Index()
        {
            var model =  db.Ilanlar.OrderByDescending(x => x.ID).ToList();
            return View(model);
        }

        public ActionResult Add()
        {
            
            return View();
        }

        const string imageFolderPath = "/Content/ilanlar-images/";
        public ActionResult AddIlan(IlanlarModel model)
        {
            if (ModelState.IsValid)
            {
                string fileName = string.Empty;
                //Dosya kaydetme
                if (model.Resim != null && model.Resim.ContentLength > 0)
                {
                    fileName = model.Resim.FileName;
                    var path = Path.Combine(Server.MapPath("~" + imageFolderPath), fileName);
                    model.Resim.SaveAs(path);
                }

                Ilanlar ilanlar = new Ilanlar();
                ilanlar.fiyat = model.fiyat;
                ilanlar.Ilce = model.Ilce;
                ilanlar.kisaYazi = model.kisaYazi;
                ilanlar.Sehir = model.Sehir;
                ilanlar.SirketAdi = model.SirketAdi;
                ilanlar.ResimYolu = imageFolderPath + fileName;

                db.Ilanlar.Add(ilanlar);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = db.Ilanlar.Find(id);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Ilanlar model)
        {
            if (ModelState.IsValid)
            {
                db.Ilanlar.Attach(model);
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {

            var model = db.Ilanlar.Find(id);

            return View(model);
        }

        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {

            var model = db.Ilanlar.Find(id);
            db.Ilanlar.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

DogruProjeSon/eyikat.com/DogruProje/eYikat/eYikat/Areas/Admin/Controllers/RolYonetimController.cs
using eYikat.Areas.Admin.Models;
using eYikat.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eYikat.Areas.Admin.Controllers
{
    [Authorize(Roles = "yonetici")]
    public class RolYonetimController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        // GET: Admin/RolYonetim
        public ActionResult Index()
        {
            var roleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(roleStore);

            var model = roleManager.Roles.ToList();

            return View(model);
        }

        public ActionResult RolEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RolEkle(RolEkleModel rol)
        {
            var roleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(roleStore);

            if (roleManager.RoleExists(rol.RolAd) == false)
            {
                roleManager.Create(new IdentityRole(rol.RolAd));
            }

            return RedirectToAction("Index");
        }

        public ActionResult RolKullaniciEkle()
        {

            return View();
        }

        [HttpPost]
        public ActionResult RolKullaniciEkle(RolKullaniciEkleModel model)
        {
            var roleStore = new RoleStore<IdentityRole>(context);
            var roleManager = new RoleManager<IdentityRole>(roleStore);

            var userStore = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(userStore);

            var kullanici = userManager.FindByName(model.KullaniciAdi);

            if (!userManager.IsInRole(kullanici.Id , model.RolAdi)) //Zaten bu roldeyse hiç bir şey yapma
            {
                userManager.AddToRole(kullanici.Id, model.RolAdi);
            }


            return RedirectToAction("Index");
        }

    }
}

DogruProjeSon/eyikat.com/DogruProje/eYikat/eYikat/Areas/Admin/Controllers/SliderController.cs
using eYikat.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eYikat.Areas.Admin.Controllers
{
    [Authorize(Roles = "yonetici")]
    public class SliderController : Controller
    {
        eYikatEntities2 db = new eYikatEntities2();
        // GET: Admin/Slider
        public ActionResult Index()
        {
            var model = db.Slider.OrderByDescending(x=>x.ID).ToList();

            return View(model);
        }

        public ActionResult Add()
        {
            return View();
        }

        const string imageFolderPath = "/Content/slider-images/";

        /// <summary>
        /// Post ile gelen model bu metodda işlidir
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult AddSlider(SliderModel model)
        {
            if (ModelState.IsValid)
            {
                string fileName = string.Empty;
                //Dosya kaydetme
                 if (model.SliderFoto != null && model.SliderFoto.ContentLength > 0)
                {
                    fileName = model.SliderFoto.FileName;
                    var path = Path.Combine(Server.MapPath("~" + imageFolderPath),fileName);
                    model.SliderFoto.SaveAs(path);
                }

                //EF nesnesi oluştruma
                Slider slider = new Slider();
                slider.SliderText = model.SliderText;
                slider.ResimYolu = imageFolderPath+fileName;

                db.Slider.Add(slider);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model =  db.Slider.Find(id);
             
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Slider model)
        {
            if (ModelState.IsValid)
            {
                db.Slider.Attach(model);
                db.Entry(model).State = System.Data.Entity.EntityState.Modified; 
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {

            var model = db.Slider.Find(id);

            return View(model);
        }

        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {

            var model = db.Slider.Find(id);
            db.Slider.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index"); 
        }

    }
}

DogruProjeSon/eyikat.com/DogruProje/eYikat/eYikat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - eYikat.com</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("eYikat.com", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ana Sayfa", "Index", "Home")</li>
                    <li>@Html.ActionLink("Temizlet", "urunler", "Home")</li>
                    <li>@Html.ActionLink("İletişim", "Contact", "Home")</li>
                    <li>@Html.ActionLink("İlan Ver", "ilanver", "Home")</li>

                    
                </ul>

                @if (ViewContext.HttpContext.User.IsInRole("yonetici"))
                {
                    
                        <button type="button" class="btn btn-success btn-lg dropdown-toggle" data-toggle="dropdown">Admin Panel <span class="caret"></span></button>

                        <ul class="dropdown-menu">
                            <li class="dropdown-header">Yönetim</li>

                            <li>@Html.ActionLink("AnaSayfa", "Index", "AdminHome", new { Area = "Admin" }, new { })  </li>
                            <li>@Html.ActionLink("Slider Ekle", "Add", "Slider", new { Area = "Admin" }, new { })  </li>
                            <li>@Html.ActionLink("Slider Düzenle", "Index", "Slider", new { Area = "Admin" }, new { })  </li>
                            <li>@Html.ActionLink("Urun Ekle", "Add", "Ilanlar", new { Area = "Admin" }, new { })  </li>
                            <li>@Html.ActionLink("Urun Düzenle", "Index", "Ilanlar", new { Area = "Admin" }, new { })  </li>


                            <li class="divider"></li>

                            <li class="dropdown-header">Rol Yönetimi</li>

                            <li>@Html.ActionLink("Roller", "Index", "RolYonetim", new { Area = "Admin" }, new { })  </li>
                            <li>@Html.ActionLink("Rol Ekle", "RolEkle", "RolYonetim", new { Area = "Admin" }, new { })  </li>
                            <li>@Html.ActionLink("Kullanıcı Rol Ekle", "RolKullaniciEkle", "RolYonetim", new { Area = "Admin" }, new { })  </li>


                        </ul>
                   
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Copyright c 2016-2023 eYıkat.com</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>